#undef MOUSEKEY_DELAY
#undef MOUSEKEY_TIME_TO_MAX
#undef TAPPING_TERM

#define LSPO_KEY KC_9
#define RSPC_KEY KC_0
#define PERMISSIVE_HOLD
#define LEADER_TIMEOUT 300
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_TIME_TO_MAX 30
#define MOUSEKEY_WHEEL_TIME_TO_MAX 255
#define MOUSEKEY_WHEEL_MAX_SPEED 4
#define TAPPING_TERM 175